### ISSUE TITLE
Supporting .Net 6 and up

### ISSUE THREAD

**Issue by darcon77** [Open-NET-Libraries/Open.ChannelExtensions#29]
Is there a plan to target .Net 6 and remove the dependency on System.Threading.Channels 6.0.0, since frameworks .Net 6 and up ship with System.Threading.Channels?

**Comment by electricessence** [comment]
I'm careful to update a lower version unless there's a serious reason for it.  You should without any issue be able use (local update) any version higher than 6.0.0 and it work fine.  It can seem a little less elegant than just importing the major version, but since this library is entirely NET Standard 2.0 and 2.1, there's nothing preventing it from being used by any version of .NET.

I am considering a leap to multi-target .NET 8, because of all the improvements and potential performance benefits.
May end up working on that this week.  Stay tuned.

**Comment by electricessence** [comment]
It's done.  I did it.  Thank you.  You're welcome. :)
Released final 6.3 version.
Released v7 to support Channels 7.
Released v8 to support Channels 8.
Targets: NET Standard 2.0 and 2.1, NET 6, and NET 8.
https://www.nuget.org/packages/Open.ChannelExtensions/8.0.0
